# AUTO-GENERATED by fortran/generate_esr_potentials.py -- DO NOT EDIT BY HAND.
# Maps 'runname/compl_c' (the two path components under function_library/)
# to the integer library id compiled into esr_potentials.f90.
LIBRARY_IDS = {
    'B_maths/compl_4': 0,
    'DE_maths/compl_4': 1,
    'V_maths/compl_4': 2,
    'V_maths/compl_5': 3,
}
