"""Generate a Fortran module of analytic ESR potentials F(phi), F'(phi), F''(phi).

This replaces the runtime interpolation-table approach of TQuintessenceInterp: instead of
building spline tables in Python and interpolating in Fortran, every candidate function in the
ESR libraries is compiled once into camblib and evaluated analytically, selected at runtime by
(library, index). Adapted from the old CLASS w-reconstruction helper (helpers/C_generator.py),
but emits Fortran (CAMB's build is Fortran-only) and covers up to the 2nd derivative.

Design guarantees:
  * index alignment: case (idx) == line number in the unique_equations file (NO renumbering).
    Invalid / constant-in-phi / singular entries are emitted as NaN stubs, never skipped, so
    esr_potential_index keeps its meaning across the whole pipeline.
  * sympy's single-argument sign() (from d/dx|g|) is mapped to an esr_sign helper
    (Fortran's intrinsic sign is two-argument).
  * functions whose derivative cannot be printed (e.g. DiracDelta from differentiating sign)
    are stubbed to NaN; the caller (TQuintessenceInterp) must treat NaN as a rejected point.

Regenerate after changing the function libraries:
    python fortran/generate_esr_potentials.py
Outputs:
    fortran/esr_potentials.f90      (compiled into camblib, module esr_potentials)
    camb/_esr_libmap.py             (library-path -> integer id, used by dark_energy.py)
"""
import os
import sys
import io
import contextlib

import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)
from camb.dark_energy import load_esr_function_string  # noqa: E402

X = sp.Symbol('x', real=True)
NPAR = 4                       # a0..a3
FLIB_ROOT = os.path.join(REPO, 'function_library')
OUT_F90 = os.path.join(HERE, 'esr_potentials.f90')
OUT_MAP = os.path.join(REPO, 'camb', '_esr_libmap.py')


def fortran_expr(expr):
    """Free-form Fortran for a sympy expr, with a0..a3 -> a(0:3) and sign -> esr_sign."""
    subs = {sp.Symbol(f'a{i}', real=True): sp.Symbol(f'a__{i}') for i in range(NPAR)}
    code = sp.fcode(expr.subs(subs), standard=2008, source_format='free',
                    user_functions={'sign': 'esr_sign'})
    code = code.replace('&', ' ')
    code = ' '.join(code.split())
    for i in range(NPAR):
        code = code.replace(f'a__{i}', f'a({i})')
    return code


def function_codes(path, idx):
    """Return [F, dF, ddF] Fortran strings for line idx, or None if it must be stubbed."""
    with contextlib.redirect_stdout(io.StringIO()):
        fd = load_esr_function_string(path, idx)
    if not fd.get('valid'):
        return None
    expr = fd['expr_template']
    if X not in expr.free_symbols:            # constant in phi: no coupling, treat as invalid
        return None
    try:
        codes = [fortran_expr(expr),
                 fortran_expr(sp.diff(expr, X)),
                 fortran_expr(sp.diff(expr, X, 2))]
    except Exception:
        return None
    if any(('Piecewise' in c or 'merge' in c or 'Dirac' in c) for c in codes):
        return None
    return codes


def discover_libraries(root):
    """Map 'runname/compl_c' -> absolute unique_equations path, sorted for stable ids."""
    libs = {}
    for dirpath, _, files in os.walk(root):
        for fn in files:
            if fn.startswith('unique_equations_') and fn.endswith('.txt'):
                key = os.path.relpath(dirpath, root)
                libs[key] = os.path.join(dirpath, fn)
    return dict(sorted(libs.items()))


def count_lines(path):
    with open(path) as f:
        return sum(1 for ln in f if ln.strip())


def main():
    libs = discover_libraries(FLIB_ROOT)
    if not libs:
        raise SystemExit(f'No unique_equations_*.txt under {FLIB_ROOT}')

    lib_ids = {key: i for i, key in enumerate(libs)}
    total_ok = total_stub = 0

    with open(OUT_F90, 'w') as f:
        f.write("! AUTO-GENERATED by fortran/generate_esr_potentials.py -- DO NOT EDIT BY HAND.\n")
        f.write("! Analytic ESR potentials F(phi) and derivatives, selected by (library, index).\n")
        f.write("! (library, index) map is emitted to camb/_esr_libmap.py; index == line number\n")
        f.write("! in the unique_equations file. NaN return => invalid/singular entry to reject.\n")
        f.write("module esr_potentials\n")
        f.write("    use precision, only: dl\n")
        f.write("    use, intrinsic :: ieee_arithmetic\n")
        f.write("    implicit none\n    private\n")
        f.write("    public :: esr_eval, esr_nlib\n")
        f.write(f"    integer, parameter :: esr_nlib = {len(libs)}\n")
        f.write("contains\n\n")
        f.write("    elemental real(dl) function esr_sign(x) result(s)\n")
        f.write("        real(dl), intent(in) :: x\n")
        f.write("        if (x > 0) then\n            s = 1.0_dl\n")
        f.write("        else if (x < 0) then\n            s = -1.0_dl\n")
        f.write("        else\n            s = 0.0_dl\n        end if\n")
        f.write("    end function esr_sign\n\n")
        f.write("    ! F(phi) [deriv=0], dF/dphi [1], d2F/dphi2 [2] for (lib, idx).\n")
        f.write("    ! Returns NaN for invalid/constant/singular entries; caller must reject.\n")
        f.write("    real(dl) function esr_eval(lib, idx, deriv, x, a) result(y)\n")
        f.write("        integer, intent(in) :: lib, idx, deriv\n")
        f.write("        real(dl), intent(in) :: x\n")
        f.write("        real(dl), intent(in) :: a(0:3)\n")
        f.write("        y = ieee_value(y, ieee_quiet_nan)\n")
        f.write("        select case (lib)\n")
        for key, path in libs.items():
            lib = lib_ids[key]
            n = count_lines(path)
            f.write(f"        case ({lib})  ! {key}  ({n} entries)\n")
            f.write("            select case (idx)\n")
            for idx in range(n):
                codes = function_codes(path, idx)
                if codes is None:
                    total_stub += 1
                    continue
                total_ok += 1
                f.write(f"            case ({idx})\n")
                f.write("                select case (deriv)\n")
                for d, c in enumerate(codes):
                    f.write(f"                case ({d}); y = {c}\n")
                f.write("                end select\n")
            f.write("            end select\n")
        f.write("        end select\n")
        f.write("    end function esr_eval\n")
        f.write("end module esr_potentials\n")

    with open(OUT_MAP, 'w') as f:
        f.write("# AUTO-GENERATED by fortran/generate_esr_potentials.py -- DO NOT EDIT BY HAND.\n")
        f.write("# Maps 'runname/compl_c' (the two path components under function_library/)\n")
        f.write("# to the integer library id compiled into esr_potentials.f90.\n")
        f.write("LIBRARY_IDS = {\n")
        for key, i in lib_ids.items():
            f.write(f"    {key!r}: {i},\n")
        f.write("}\n")

    print(f"Wrote {OUT_F90}")
    print(f"Wrote {OUT_MAP}")
    for key, i in lib_ids.items():
        print(f"  lib {i}: {key}  ({count_lines(libs[key])} entries)")
    print(f"Total: {total_ok} analytic functions, {total_stub} stubbed (invalid/constant/singular).")


if __name__ == '__main__':
    main()
